// Code generated by MockGen. DO NOT EDIT.
// Source: ec2id.go

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"

	ec2 "github.com/aws/aws-sdk-go-v2/service/ec2"
	gomock "github.com/golang/mock/gomock"
)

// MockEC2DescribeInstancesAPI is a mock of EC2DescribeInstancesAPI interface.
type MockEC2DescribeInstancesAPI struct {
	ctrl     *gomock.Controller
	recorder *MockEC2DescribeInstancesAPIMockRecorder
}

// MockEC2DescribeInstancesAPIMockRecorder is the mock recorder for MockEC2DescribeInstancesAPI.
type MockEC2DescribeInstancesAPIMockRecorder struct {
	mock *MockEC2DescribeInstancesAPI
}

// NewMockEC2DescribeInstancesAPI creates a new mock instance.
func NewMockEC2DescribeInstancesAPI(ctrl *gomock.Controller) *MockEC2DescribeInstancesAPI {
	mock := &MockEC2DescribeInstancesAPI{ctrl: ctrl}
	mock.recorder = &MockEC2DescribeInstancesAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEC2DescribeInstancesAPI) EXPECT() *MockEC2DescribeInstancesAPIMockRecorder {
	return m.recorder
}

// DescribeInstances mocks base method.
func (m *MockEC2DescribeInstancesAPI) DescribeInstances(ctx context.Context, params *ec2.DescribeInstancesInput, optFns ...func(*ec2.Options)) (*ec2.DescribeInstancesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeInstances", varargs...)
	ret0, _ := ret[0].(*ec2.DescribeInstancesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeInstances indicates an expected call of DescribeInstances.
func (mr *MockEC2DescribeInstancesAPIMockRecorder) DescribeInstances(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeInstances", reflect.TypeOf((*MockEC2DescribeInstancesAPI)(nil).DescribeInstances), varargs...)
}
